language: go

go:
  - 1.13.0
  - tip

before_install:
  - go get -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)