name: Build pasteme-cli

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux_amd64:
    name: Build pasteme-cli on linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build pasteme-cli on linux/amd64
        run: go build -v -o build/pasteme-cli-linux-amd64

      - name: Test
        run: go test -v .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: build/
  windows_amd64:
    name: Build pasteme-cli on windows/amd64
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build pasteme-cli on windows/amd64
        run: go build -v -o build/pasteme-cli-windows-amd64.exe

      - name: Test
        run: go test -v .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: build/
  darwin_amd64:
    name: Build pasteme-cli on darwin/amd64
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Build pasteme-cli on darwin/amd64
        run: go build -v -o build/pasteme-cli-darwin-amd64

      - name: Test
        run: go test -v .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: build/